GrayBShop/GrayBShop/Controllers/AccountUserController.cs
using GrayBShop.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GrayBShop.Controllers
{
    public class AccountUserController : Controller
    {
        GrayShop db = new GrayShop();
        // GET: AccountUser
        [HttpGet]
        public ActionResult ChangePassWord()
        {
            if (Session[GrayBShop.Session.ConstainUser.USER_SESSION] == null || Session[GrayBShop.Session.ConstainUser.USER_SESSION].ToString() == "")
            {
                return RedirectToAction("Login", "Home");
            }
            return View();
        }

        [HttpPost]
        public ActionResult ChangePassWord(string oldpassword, string password)
        {
            User tk = (User)Session[GrayBShop.Session.ConstainUser.USER_SESSION];
            if (tk.Password != oldpassword)
            {
                ModelState.AddModelError("ErrorUpdate", "Mật khẩu cũ không đúng");
            }
            else
            {
                User edit = db.Users.Where(a => a.UserID.Equals(tk.UserID)).FirstOrDefault();
                edit.Password = password;
                db.SaveChanges();
                Session[GrayBShop.Session.ConstainUser.USER_SESSION] = edit;
                ModelState.AddModelError("ErrorUpdate", "Đổi mật khẩu thành công!");
            }
            return View();
        }


        [HttpGet]
        public ActionResult UserInfor(int id)
        {
            User session = (User)Session[GrayBShop.Session.ConstainUser.USER_SESSION];
            if (session == null)
            {
                return RedirectToAction("PageNotFound", "Error");
            }
            else
            {
                User tk = db.Users.Where(a => a.UserID.Equals(id)).FirstOrDefault();
                return View(tk);
            }
        }

        [HttpPost]
        public ActionResult UserInfor([Bind(Include = "UserID,Name,Phone,Address,Email")] User tk)
        {
            User edit = db.Users.Where(a => a.UserID.Equals(tk.UserID)).FirstOrDefault();
            try
            {
                edit.Name = tk.Name;
                edit.Address = tk.Address;
                edit.Email = tk.Email;
                edit.Phone = tk.Phone;
                db.SaveChanges();
                Session[GrayBShop.Session.ConstainUser.USER_SESSION] = edit;
            }
            catch (Exception)
            {
                ModelState.AddModelError("ErrorUpdate", "Cập nhật thông tin không thành công ! Thử lại sau !");
            }
            return View(edit);
        }
    }
}

GrayBShop/GrayBShop/Views/AccountUser/ChangePassWord.cshtml
@{
    ViewBag.Title = "ChangePassWord";
    Layout = "~/Views/Share/_LayoutClient.cshtml";
}

<div class="image-login">
    <div class="container">
        <div class="account">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="login">
                    <h1 class="account-title">Đổi mật khẩu</h1>
                    @using (Html.BeginForm("ChangePassWord", "AccountUser", FormMethod.Post, new { onsubmit = "return checkPass();" }))
                    {
        @Html.ValidationMessage("ErrorUpdate", new { @class = "text-danger", @id = "error-message" })
                        <hr />
                                        <div class="clearfix large_form">
                                            <label class="icon-field">
                                                <i class="fas fa-lock"></i>
                                            </label>
                                            <input type="password" name="oldpassword" required class="form-control" id="oldpassword" placeholder="Mật khẩu cũ">
                                        </div>
                                                        <div class="clearfix large_form">
                                                            <label class="icon-field">
                                                                <i class="fas fa-lock"></i>
                                                            </label>
                                                            <input type="password" name="password" required class="form-control" id="password" placeholder="Mật khẩu mới">
                                                        </div>
                                                                        <div class="clearfix large_form">
                                                                            <label class="icon-field">
                                                                                <i class="fas fa-lock"></i>
                                                                            </label>
                                                                            <input type="password" class="form-control" required name="confirmpassword" id="confirmpassword" placeholder="Xác nhận mật khẩu">
                                                                        </div> <!-- <p class="lost-password"><a href="forgot-password.html">Forgot password?</a></p> --><br />
                                                                                        <div class="clearfix large_form">
                                                                                            <input class="btn btn-signin" type="submit" value="Đổi mật khẩu" style="width:100%;background:#33b5e5;">
                                                                                        </div>}


                </div>
            </div>

        </div>

    </div>
</div>


<script>function checkPass() {
        if (document.getElementById("password").value != document.getElementById("confirmpassword").value) {
            document.getElementById("error-message").innerHTML = "Mật khẩu không khớp";
            return false;
        }
        return true;
    }</script>

GrayBShop/GrayBShop/Views/AccountUser/UserInfor.cshtml
@model GrayBShop.Models.User

@{ ViewBag.Title = "Thông tin tài khoản";
    Layout = "~/Views/Share/_LayoutClient.cshtml";
 }


<div class="image-login">
    <div class=" container">
        <div class="account">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="login">
                    <h1 class="account-title">Thông tin khách hàng</h1>

                    @using (Html.BeginForm())
                    {
        @Html.AntiForgeryToken()
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                        @Html.HiddenFor(model => model.UserID)
                                                        <div class="clearfix large_form">

                                                            <label class="icon-field">
                                                                <i class="fas fa-user"></i>
                                                            </label>
                                                            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                                                            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                                                        </div>
                                                                        <div class="clearfix large_form">
                                                                            <label class="icon-field">
                                                                                <i class="fas fa-map-marker-alt"></i>
                                                                            </label>
                                                                            @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                                                                            @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
                                                                        </div>


                                                                                        <div class="clearfix large_form">
                                                                                            <label class="icon-field">
                                                                                                <i class="far fa-envelope"></i>
                                                                                            </label>
                                                                                            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                                                                                            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })<br />
                                                                                        </div>
                                                                                                        <div class="clearfix large_form">
                                                                                                            <label class="icon-field">
                                                                                                                <i class="fas fa-mobile-alt"></i>
                                                                                                            </label>
                                                                                                            @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                                                                                                            @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
                                                                                                        </div>

                                                                                                                        <div class="clearfix large_form">
                                                                                                                            <input class="btn btn-signin" type="submit" value="Cập nhật" style="width:100%;background:#33b5e5;">
                                                                                                                        </div>}
                </div>




            </div>
        </div>

    </div>
</div>